name: Release
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
    with:
      persist-credentials: false
  - uses: actions/setup-node@v1
    with:
      node-version: "14.x"
  - run: npm install
  - run: npm run build
  - run: npm test
  - run: npm run e2e
  - run: npm run semantic-release
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      BUGSPLAT_USER: ${{ secrets.BUGSPLAT_USER }}
      BUGSPLAT_PASSWORD: ${{ secrets.BUGSPLAT_PASSWORD }}
      BUGSPLAT_DATABASE: ${{ secrets.BUGSPLAT_DATABASE }}
      BUGSPLAT_CLIENT_ID: ${{ secrets.BUGSPLAT_CLIENT_ID }}
      BUGSPLAT_CLIENT_SECRET: ${{ secrets.BUGSPLAT_CLIENT_SECRET }}